name: Deploy Powpow
on:
  workflow_dispatch:
env:
  REPO_NAME: ${{ github.event.repository.name }}
jobs:
  install-requirements:
    runs-on: ubuntu-latest
    steps:
      - name: Installing requirements for ${{env.REPO_NAME}}
        uses: fifsky/ssh-action@master
        with:
          command: |
            apt update -y
            apt install nodejs -y
            apt install npm -y
            npm install -g ts-node
          host: ${{secrets.HOST}}
          user: root
          key: ${{secrets.SSH_PRIVATE_KEY}}

  deploy-to-vultr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: SFTPVultrDeploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.1
        with:
          username: root
          server: ${{secrets.HOST}}
          port: 22
          ssh_private_key: ${{secrets.SSH_PRIVATE_KEY}}
          local_path: ./*
          remote_path: /root/${{env.REPO_NAME}}
          args: "-o ConnectTimeout=5"

  add-env-variables:
    needs: [deploy-to-vultr]
    runs-on: ubuntu-latest
    timeout-minutes: 2
    env:
      POWPOW_TOKEN: ${{secrets.POWPOW_TOKEN}}
      GUILD_ID: ${{secrets.GUILD_ID}}
      OPENAI_KEY: ${{secrets.OPENAI_KEY}}
      POWPOW_DISCORD_ID: ${{secrets.POWPOW_DISCORD_ID}}
    steps:
      - id: add-env-variables
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd ${{env.REPO_NAME}}
            touch .env
            echo TOKEN=${{env.POWPOW_TOKEN}} > .env
            echo GUILD_ID=${{env.GUILD_ID}} > .env
            echo OPENAI_API_KEY=${{env.OPENAI_KEY}} > .env
            echo CLIENT_ID=${{env.POWPOW_DISCORD_ID}} > .env
            echo $?
          host: ${{secrets.HOST}}
          user: root
          key: ${{secrets.SSH_PRIVATE_KEY}}

  install-npm-packages:
    needs: [add-env-variables, deploy-to-vultr]
    runs-on: ubuntu-latest
    steps:
      - id: create-systemctl-service
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd ${{env.REPO_NAME}}
            npm install
        host: ${{secrets.HOST}}
        user: root
        key: ${{secrets.SSH_PRIVATE_KEY}}
