name: Update
on:
  push:
    branches: [master]
env:
  REPO_NAME: ${{ github.event.repository.name }}
jobs:
  deploy-to-vultr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: SFTPVultrDeploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.1
        with:
          username: root
          server: ${{secrets.HOST}}
          port: 22
          ssh_private_key: ${{secrets.SSH_PRIVATE_KEY}}
          local_path: ./*
          remote_path: /root/${{env.REPO_NAME}}
          args: "-o ConnectTimeout=5"

  install-npm-packages:
    needs: [deploy-to-vultr]
    runs-on: ubuntu-latest
    steps:
      - id: create-systemctl-service
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd ${{env.REPO_NAME}}
            npm install
          host: ${{secrets.HOST}}
          user: root
          key: ${{secrets.SSH_PRIVATE_KEY}}

  start-bot:
    needs: [install-npm-packages, deploy-to-vultr]
    runs-on: ubuntu-latest
    steps:
      - id: create-systemctl-service
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd ${{env.REPO_NAME}}
            npm start
          host: ${{secrets.HOST}}
          user: root
          key: ${{secrets.SSH_PRIVATE_KEY}}
